name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-15
            artifact: nfdtonfc.app/Contents/MacOS/nfdtonfc
            release-name: nfdtonfc-macos
          - os: windows-2025
            artifact: nfdtonfc/nfdtonfc.exe
            release-name: nfdtonfc-windows.exe
          - os: ubuntu-24.04
            artifact: nfdtonfc/bin/nfdtonfc
            release-name: nfdtonfc-ubuntu

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-java@v5.2.0
        with:
          java-version: '25'
          distribution: 'zulu'

      - name: Grant execute permission (Unix)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build with jpackage
        run: ./gradlew jpackageImage

      - name: Rename artifact (Unix)
        if: runner.os != 'Windows'
        run: cp build/jpackage/${{ matrix.artifact }} ${{ matrix.release-name }}

      - name: Rename artifact (Windows)
        if: runner.os == 'Windows'
        run: copy build\jpackage\${{ matrix.artifact }} ${{ matrix.release-name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ matrix.release-name }}
          path: ${{ matrix.release-name }}

  release:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/download-artifact@v8.0.1
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v3.0.0
        with:
          files: |
            artifacts/nfdtonfc-macos/nfdtonfc-macos
            artifacts/nfdtonfc-windows.exe/nfdtonfc-windows.exe
            artifacts/nfdtonfc-ubuntu/nfdtonfc-ubuntu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
